#!/bin/bash

if [[ ! -f ./.config ]]; then
	echo ".config file is either missing or inaccessible"
	exit 1
else
	source ./.config
fi


domain_id=$(curl -sX GET "https://api.cloudflare.com/client/v4/zones" \
	-H "X-Auth-Email: $AuthEmail" \
	-H "X-Auth-Key: $AuthKey" \
	-H "Content-Type: application/json" | jq -r --arg domain "$domain" '.["result"] | .[] | select(.name==$domain) | .id')

if [[ ! -z $subdomain ]]; then
	domain="${subdomain}.${domain}"
fi
read -r live_record live_record_id < <(curl -sX GET "https://api.cloudflare.com/client/v4/zones/${domain_id}/dns_records" \
	-H "X-Auth-Email: $AuthEmail" \
	-H "X-Auth-Key: $AuthKey" \
	-H "Content-Type: application/json" | jq -r --arg domain "$domain" --arg record_type "$record_type" '.["result"] | .[] | select(.name==$domain and .type==$record_type) | .content,.id' | tr '\n' ' ')

our_ip=$(dig +short myip.opendns.com @resolver1.opendns.com)

if [[ $live_record == $our_ip ]]; then
	echo "yay, same ip!"
else
	echo "ip differs, updating"
	json_request="{\"type\":\"${record_type}\",\"name\":\"${domain}\",\"content\":\"${our_ip}\"}"

	curl -X PUT "https://api.cloudflare.com/client/v4/zones/${domain_id}/dns_records/${live_record_id}" \
		-H "X-Auth-Email: $AuthEmail" \
		-H "X-Auth-Key: $AuthKey" \
		-H "Content-Type: application/json" \
		--data ${json_request}
fi


#echo "Domain: $domain
#ID: $domain_id
#Live record: ${live_record}
#Live record id: $live_record_id
#Our IP: $our_ip
#Record type: $record_type"
